<a href="https://colab.research.google.com/github/asbin77/machine_learning_cfe/blob/main/assignment_numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
mat=np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]
              ])
#Extract the first two row
mat[0:2,:]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
# Extract the last two columns
mat[:,2:]


array([[ 30,  40],
       [ 70,  80],
       [110, 120]])

In [6]:
# Extract the center 2×2 block (values 60, 70, 100, 110)
mat[1:,1:3]

array([[ 60,  70],
       [100, 110]])

In [7]:
# Reverse all rows
mat[:,::-1]

array([[ 40,  30,  20,  10],
       [ 80,  70,  60,  50],
       [120, 110, 100,  90]])

In [8]:
# Use boolean indexing to extract all values greater than 60
mat[::-1,:]

array([[ 90, 100, 110, 120],
       [ 50,  60,  70,  80],
       [ 10,  20,  30,  40]])

In [9]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])


In [10]:
# Add array b to each row of array a using broadcasting
mat=a+b
print(mat)

[[11 22 33]
 [14 25 36]]


In [11]:
# Multiply array a by 2
res=a*2
print(res)

[[ 2  4  6]
 [ 8 10 12]]


In [13]:
# Calculate the mean, sum, and standard deviation of array a
mean=a.mean()
print(mean)
add=a.sum()
print(add)
sd=a.std()
print(sd)

3.5
21
1.707825127659933


In [14]:
# Find the maximum value in each column of array a
a.argmax(axis=0)

array([1, 1, 1])

In [15]:
# Find the minimum value in each row of array a
a.argmin(axis=1)

array([0, 0])

In [16]:
# Compare which elements in array a are greater than 3 (use comparison operators)
x=a[a>3]
print(x)

[4 5 6]
