<a href="https://colab.research.google.com/github/asbin77/machine_learning_cfe/blob/main/assignment_numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Array Creation Practice
Create the following arrays using different NumPy functions:


In [1]:
import numpy as np


In [13]:
# A 1D array with values from 10 to 50 with a step of 5 using np.arange()

a=np.array([1,10])
print(a)
np.arange(10,50,5)


[ 1 10]


array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
# A 3x3 identity matrix using np.eye()
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# A 4x5 array filled with the value 7 using np.full()
np.full((4,5),fill_value=7,dtype=np.int32)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]], dtype=int32)

In [22]:
# A 1D array with 8 evenly spaced values between 0 and 100 using np.linspace()
np.linspace(0,100,8)

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

# 2. Practical Application
Simulate a simple gradebook system:



In [31]:
# Create a 2D array representing 5 students and their marks in 4 subjects
# rows=student_name
# column=sub_name
# sub_name=eng,nep,phy,Math
# student_name=s1,s2,s3,s4,s5
marks=np.array([[67,73,85,92],
               [54,97,52,69],
               [86,84,93,90],
               [95,89,92,93],
               [85,80,85,83]])
print(marks)

[[67 73 85 92]
 [54 97 52 69]
 [86 84 93 90]
 [95 89 92 93]
 [85 80 85 83]]


In [40]:
# Calculate and print:
# Average marks for each student
avg_marks_student=np.mean(marks,axis=1)
print(avg_marks_student)
# Average marks for each subject
avg_marks_subjects=np.mean(marks,axis=0)
print(avg_marks_subjects)
# Identify which student has the highest total marks
total_marks=np.sum(marks,axis=1)
highest_student=np.argmax(total_marks)
students = ["S1", "S2", "S3", "S4", "S5"]
print("Highest marks scored by:", students[highest_student])


[79.25 68.   88.25 92.25 83.25]
[77.4 84.6 81.4 85.4]
Highest marks scored by: S4
